name: currency_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # di
  get_it: ^7.7.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.6
  # hive
  hive: ^2.2.3
  # rest api
  dio: ^5.6.0
  dio_retry_plus: ^2.0.7
  # http parser
  http_parser: ^4.0.2
  # chuck
  chuck_interceptor: ^2.1.7
  # box
  gap: ^3.0.1
  # router
  go_router: ^14.2.3
  # map launcher
  map_launcher: ^3.4.0
  # url launchers
  url_launcher: ^6.3.0
  # firebase
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_remote_config: ^5.0.4
  # local notification
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0
  geolocator: ^12.0.0
  location: ^6.0.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/AppIcons.ttf
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Medium.ttf
    - assets/fonts/Montserrat-SemiBold.ttf
    - assets/fonts/Montserrat-Bold.ttf
    - assets/locale/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
